### ISSUE TITLE
用这两个算法的人太少了

### ISSUE THREAD

**Issue by riverai** [Srar/node-tap#15]
之前用这两个的服务器估计都被墙了，后来大家都换成了比较新的加密算法。

**Comment by Srar** [comment]
后续会添加nodejs官方已支持的算法. 

如chacha20目前nodejs官方未支持暂不考虑添加

**Comment by Srar** [comment]
aes-128-gcm, aes-192-gcm, aes-256-gcm加密方式已push到dev分支
