### ISSUE TITLE
Dev 分支是否考虑编译打包？

### ISSUE THREAD

**Issue by Vanww** [Srar/node-tap#16]
尝试编译 ，遇到许多错误，尝试解决无果

是否可以提供？或建立一个 Wiki 页面详细说明如何编译  :smile:

**Comment by Srar** [comment]
会后续在ReadMe中加入如何编译。

**Comment by Srar** [comment]
已添加打包教程.

[如何打包成可执行文件](https://github.com/Srar/node-tap/wiki/%E5%A6%82%E4%BD%95%E6%89%93%E5%8C%85%E6%88%90%E5%8F%AF%E6%89%A7%E8%A1%8C%E6%96%87%E4%BB%B6)
