### ISSUE TITLE
跑起来后查询ip还是本机ip

### ISSUE THREAD

**Issue by vincent4web** [Srar/node-tap#23]
这个是不是没作用？

**Comment by Srar** [comment]
麻烦在`cmd`或者`powershell`中输入`ROUTE.EXE print`然后截图 然后启动tap时候的参数和输出也一并截图.

**Comment by Srar** [comment]
也请注意不要选中`cmd`或者`powershell`中的任何字符, windows10的`cmd`或`powershell`当选中字符时会阻止`stdout`继续输出, 然后阻塞nodejs主线程导致无法响应arp包. 然后windows10就认为这个网卡废了从而使用默认网卡

**Comment by vincent4web** [comment]
![1111111111](https://user-images.githubusercontent.com/19451736/40052424-73c49070-5870-11e8-926e-2f8e9a7ad9c0.png)
![2222222222](https://user-images.githubusercontent.com/19451736/40052439-7b8a6ab4-5870-11e8-8f8c-9db597a4800e.png)

**Comment by Srar** [comment]
看起来一切都是正常的, 不知道是否能提供TeamViewer？方便我来远程调试看看发生了什么.

**Comment by vincent4web** [comment]
晚点调，现在在公司，另外我是用ip138查的ip，应该是显示代理服务器的ip吧？

**Comment by Srar** [comment]
是的 应该显示代理服务器IP

**Comment by Srar** [comment]
可能是非Windows10系统的兼容问题 我刚刚在Windows Server 2008测试好像也没有效果 我看看是啥原因

**Comment by vincent4web** [comment]
我在家用的win10也是一样没效果，sstap可以正常使用~

**Comment by Srar** [comment]
那麻烦用win10的机器开下teamviewer我看看发生了啥？

**Comment by vincent4web** [comment]
833 102 782
19mn9b

**Comment by Srar** [comment]
防火墙没开或ss服务端不支持或ss服务端没开启, 阿里云安全组也有可能

**Comment by vincent4web** [comment]
果然只有win10可以开 win7用不了

**Comment by Srar** [comment]
win7 2008我还在看是啥原因导致的..因为首个版本在2008测试是正常的, 我估计可能是windows自动打补丁后出了点问题

**Comment by Srar** [comment]
昨晚远程时候出现的错误原因已经查明#24 过会push一个新版本修复这个问题

**Comment by vincent4web** [comment]
厉害厉害~ 希望最好能做个ui出来~

**Comment by Srar** [comment]
已经有一位同学使用C#做了一个GUI出来, 你可以试用下.
[https://github.com/JerryAJ/node-tap-gui](https://github.com/JerryAJ/node-tap-gui)

**Comment by Srar** [comment]
Windows7无法使用的问题可能是`npcap`的锅, 建议尝试卸载`npcap`使用[`winpcap`](https://www.winpcap.org/)尝试下

**Comment by vincent4web** [comment]
确实卸载npcap使用winpcap后可以用了！
