### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by Wang1998** [Srar/node-tap#30]
ʕ •ᴥ•ʔ Welcome to use node sstap.
$  .\sstap.exe --host xxxxx --port 8989 --passwd xxxxxx --xtudp 20 --method aes-256-cfb --tcphost xxxxxxx --tcpport 8989 --tcppasswd xxxxxxx --tcpmethod aes-256-cfb 
Route deletion failed. Code: 1168. Route: 10.198.75.255/255.255.255.255
IPv6 has been disabled.
netsh interface ipv4 set interface 3 metric=1 
netsh interface ipv6 set interface 3 metric=1 
netsh interface ipv4 set dnsservers 3 static 8.8.8.8 primary 
netsh interface ip set address name=3 static 10.198.75.60 255.255.255.0 10.198.75.61 
route delete 0.0.0.0 10.198.75.61 
route delete 8.8.8.8 
route add xxxxxxxx mask 255.255.255.255 192.168.1.1 metric 1 
route add xxxxxxxxx mask 255.255.255.255 192.168.1.1 metric 1 
netsh int ipv6 delete route ::/0 interface=3 nexthop=fd05:5dd5:b158:0b23:0000:0000:0000:0004 
netsh int ipv6 delete address interface=3 address=fd05:5dd5:b158:0b23:0000:0000:0000:0005 
XTUdp: 20
Default ip of adapter: 0.0.0.0
Default gateway of adapter: 192.168.1.1
Unhandled Rejection at: Promise Promise { <rejected> 71817629 } reason: 71817629

**Comment by Srar** [comment]
不知是否能TeamViewer供我来远程调试？

**Comment by Wang1998** [comment]
可以  927 683 058  8347

**Comment by Srar** [comment]
不知道现在你是否还可以提供远程吗？

**Comment by Wang1998** [comment]
现在可以 927 683 058        9837   @Srar

**Comment by Srar** [comment]
麻烦再发下新的链接信息, 我会尝试一个临时的解决办法

**Comment by Wang1998** [comment]
927 683 058  9837

**Comment by Srar** [comment]
抱歉时隔那么久没有回复, 目前我还没有想到如何会导致此错误发生. 不过还需要麻烦提供下别的信息: 请问下使用[sstap](https://www.sockscap64.com/sstap-enjoy-gaming-enjoy-sstap/)可以正常使用吗?

**Comment by Srar** [comment]
好的 谢谢反馈

Wang1998 <notifications@github.com>于2018年6月17日 周日15:26写道：

**Comment by Srar** [comment]
1.32版本已经发布做了下临时的处理, 有可能可以正常使用了 麻烦请试用下.

**Comment by Wang1998** [comment]
可以使用了，希望UDP多倍发包能集成到这个软件上，不需要额外安装

**Comment by Srar** [comment]
谢谢建议 以后会考虑加入自动安装.
