### ISSUE TITLE
开启服务之后打开网页会变慢

### ISSUE THREAD

**Issue by Crafsman** [Srar/node-tap#37]
为啥开启服务之后打开网页会变慢？

**Comment by Srar** [comment]
有可能是DNS转发有问题 需要等超时后系统自动切换到默认的DNS 这样就会觉得打开网页速度慢了

Yang Mingqian <notifications@github.com>于2018年7月17日 周二14:34写道：

**Comment by Crafsman** [comment]
@Srar  真的是DNS转发的问题。
我又在参数后追加了“--skipdns true”，这样速度就快了。
很感谢您！

**Comment by Crafsman** [comment]
@Srar 我还想知道，如何用visual studio 打开这个开源项目。
是要修改binding.gyp 文件吗？ 咋修改？
