### ISSUE TITLE
用哪个指令可以关闭连接

### ISSUE THREAD

**Issue by Crafsman** [Srar/node-tap#38]
我用管理员权限打卡shell，输入指令--host xxx --port xxx --passwd xxx  --xtudp x --method xxx --skipdns true，连接成功。
我想知道用哪个指令可以关闭这个连接？

因为我做了一个界面
![image](https://user-images.githubusercontent.com/15353430/42865249-6c73888a-8aac-11e8-8002-1f06650c54ea.png)

第一个按钮，调用指令进行连接。
第二个指令，断开连接。（不知道要调用哪个指令）

在有控制台的时候，关闭控制台可以断开，但是我隐藏了控制台

**Comment by Srar** [comment]
Carl+C 或者直接关闭窗口就行

Yang Mingqian <notifications@github.com>于2018年7月18日 周三14:59写道：

**Comment by Srar** [comment]
抱歉 没看到你截图 直接把进程结束就行了

王智成 <a1020938070@gmail.com>于2018年7月18日 周三15:12写道：

**Comment by Crafsman** [comment]
好的谢谢，最近一直在研究您的这个项目，很厉害，很厉害。

但是TypeScript 没接触过，看起来有点费劲。
如果有C，c++, c#，的版本就更好了。

**Comment by Srar** [comment]
C++有类似的开源项目：badvpn

Yang Mingqian <notifications@github.com>于2018年7月18日 周三16:13写道：

**Comment by Crafsman** [comment]
您有时间可不可讲一下这个项目的原理，

画画图什么的，比如流程图，

还有物理网卡 跟Npcap Lookback Adapter, TAP-Windows Adapter虚拟网卡，shadowsocks怎么进行的连接等。

**Comment by Srar** [comment]
这恐怕目前没有时间来详细描述.

**Comment by JerryAJ** [comment]
这位兄弟，可以看看我之前写的一个gui程序，主要将Srar的node-tap界面化了，并没有全部功能齐全...（个人时间原因），代码比较水，可能有坑，我看到你写的是winform，我用的是wpf，都是.NET下的，您可以了解下。
https://github.com/JerryAJ/node-tap-gui

**Comment by Crafsman** [comment]
![image](https://user-images.githubusercontent.com/15353430/42919649-40fbe594-8b56-11e8-81fe-9d928a9fb518.png)
我想换一下这个默认的图标，改成一个别的。
各位有解没？

**Comment by Srar** [comment]
Yang Mingqian <notifications@github.com>于2018年7月19日 周四11:19写道：

**Comment by Srar** [comment]
![3ecbedff-f968-431c-9e95-7890dd9ea99c](https://user-images.githubusercontent.com/12068066/42921992-49239f0a-8b51-11e8-9efc-25136c987a22.png)
