### ISSUE TITLE
如何调试运行这个项目

### ISSUE THREAD

**Issue by Crafsman** [Srar/node-tap#39]
各位大神，请问如何调试运行这个项目？我想深入解刨一下。
我有vs2017，也安装了TypeScript

**Comment by Srar** [comment]
进入项目目录运行安装依赖
```
npm install --unsafe
```

运行
```
 .\node_modules\.bin\ts-node .\test\test.ts
```

**Comment by Crafsman** [comment]
![image](https://user-images.githubusercontent.com/15353430/42925937-2d310f7c-8b73-11e8-91ae-3a01a50cf636.png)
我照您的指令打了上去，出现了这个，这是啥意思？

能不能像c++其他程序可以加断点调试的那种?

**Comment by Srar** [comment]
这个是启动参数说明

有关于typescript打断点调试方式请查别的资料

Yang Mingqian <notifications@github.com>于2018年7月19日 周四14:46写道：

**Comment by Crafsman** [comment]
这个项目，是不是只支持浏览器代理，

其他软件，比如下载软件或玩游戏时，能支持代理吗？

**Comment by Srar** [comment]
只要是tcp/udp就支持

Yang Mingqian <notifications@github.com>于2018年7月19日 周四14:55写道：

**Comment by Crafsman** [comment]
我的理解是Typescript无法获取虚拟网卡设备的的信息，
所以就用c++的方式打包成addon二进制文件（相当于一个.dll），
然后Typescript调用addon里面的函数跟数据。

我的理解对吗？

**Comment by Srar** [comment]
是的

Yang Mingqian <notifications@github.com>于2018年7月19日 周四15:35写道：
