### ISSUE TITLE
虚拟网卡

### ISSUE THREAD

**Issue by Crafsman** [Srar/node-tap#40]
TA-windows Adapter这个虚拟网卡，是自动截取physical网卡的数据吗？

是不是网络数据先经过虚拟网卡再经过physical网卡，如下：

data -> virutal adapter -> physical adapter

**Comment by Srar** [comment]
添加好路由表后系统会自动往这个网卡发数据

Yang Mingqian <notifications@github.com>于2018年7月20日 周五15:08写道：

**Comment by Crafsman** [comment]
这个 Npcp loopbak adapter有啥用啊，

我从代码里没有找到相关的时用,

它要跟TAP-windows Adapter有通信吗？

**Comment by Srar** [comment]
UDP多倍发包

Yang Mingqian <notifications@github.com>于2018年7月20日 周五15:18写道：
