### ISSUE TITLE
win10是否支持使用 winpcap 来开启多倍UDP发包呢

### ISSUE THREAD

**Issue by miniaoe** [Srar/node-tap#42]
如题，我找到了使用bat方式来安装winpcap的方法，可以集成到软件内，如果是使用Npcap还没找到可以不手动安装的情况下进行安装。

**Comment by Srar** [comment]
Windows10以下使Npcap可能会导致某个网卡直接失效. Windows10使用Winpcap可能捕获数据包时抽风. 这些屎坑都是踩出来的 不然我也想统一用一个.

**Comment by miniaoe** [comment]
这坑不好填啊
