### ISSUE TITLE
关于raw-socket 跟cap 库的问题

### ISSUE THREAD

**Issue by Crafsman** [Srar/node-tap#44]
node_modules里面有两个库一个cap，一个raw-socket，

请问这两个库分别起到了什么作用？

我在查看源代码时在filters/TimesUDP.ts中看到了，但是没看懂是什么意思

**Comment by Srar** [comment]
截网卡原始数据包 发原始数据包

Yang Mingqian <notifications@github.com>于2018年7月25日 周三12:50写道：

**Comment by Crafsman** [comment]
这个数据是从虚拟网卡中出来的吗？

**Comment by Srar** [comment]
物理网卡

Yang Mingqian <notifications@github.com>于2018年7月25日 周三12:55写道：

**Comment by Crafsman** [comment]
那么截取到的数据包，发送给谁了？
