### ISSUE TITLE
关于编译32位的问题

### ISSUE THREAD

**Issue by Crafsman** [Srar/node-tap#45]
我打算编译32位的库，遇到了一些问题；
环境：
Win7旗舰版32位，
vs2017,
nodejs 32
python 2.5
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
首先我修改了pacage.json，如下图红色圈圈所示：
![image](https://user-images.githubusercontent.com/15353430/43245160-e3cac536-90df-11e8-87a2-95d2c1827cc9.png)

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
但是当我#编译native库 “npm run compile” 时，
出现了一些问题，请问如何修改?
![image](https://user-images.githubusercontent.com/15353430/43245107-b2d7b74a-90df-11e8-826d-d435dad893f7.png)

**Comment by Srar** [comment]
尝试下`node8-win-x86`

**Comment by Crafsman** [comment]
不管用
这个问题是在在第二步npm run compile的时候出现的问题，跟第三步没关系。

**Comment by Crafsman** [comment]
npm run compile 执行的是：node-gyp rebuild

**Comment by Srar** [comment]
错误输出貌似不全

**Comment by Crafsman** [comment]
啥？

**Comment by Crafsman** [comment]
难道是python 有问题？

**Comment by Srar** [comment]
node-gyp内部处理我个人不是很清楚 我无法做解答
