### ISSUE TITLE
关于test.ts中路由配置的问题

### ISSUE THREAD

**Issue by Crafsman** [Srar/node-tap#47]
在test.ts中的注释中写道：
1.设置路由表，
2.添加自定义路由表，

我不明白，为啥已经设置路由表了，为何还要添加自定义路由表，

这个自定义路由表有何作用？

**Comment by Srar** [comment]
特定IP代理

Yang Mingqian <notifications@github.com>于2018年7月27日 周五13:20写道：

**Comment by Crafsman** [comment]
哦，假如我没有指定 特定IP代理，这块代码就不起作用了吧

**Comment by Srar** [comment]
https://github.com/Srar/node-tap/blob/master/test/test.ts#L36

会添加0.0.0.0/0全局路由
