### ISSUE TITLE
编译错误

### ISSUE THREAD

**Issue by Crafsman** [Srar/node-tap#51]
之前用node.js 8是可以编译成功的。
但是今天我换了nodejs 10，当我安装依赖 执行“npm install --unsafe”，
raw-sockt有错误生成。不知是何原因?

![capture](https://user-images.githubusercontent.com/15353430/43622924-01a0d90e-9722-11e8-99de-334ca9dd4cfe.PNG)

**Comment by Srar** [comment]
node版本更新 内部v8版本也会更新 v8更新后会修改少量API
