### ISSUE TITLE
关于读取和写入raw数据的问题

### ISSUE THREAD

**Issue by Crafsman** [Srar/node-tap#54]
这是`test.ts` 文件中 281行的代码：

![sse](https://user-images.githubusercontent.com/15353430/44439895-fe3a8f80-a608-11e8-8032-5929a0d089af.PNG)
这几个`data`变量我有些不理解。

1. 第一个是从虚拟网卡中读取的Raw数据，

2. 第二个也是？

3.  第三个写进虚拟网卡的`data`是请求返回来的，经过解密的数据吗？

**Comment by Srar** [comment]
1，2中间件功能给raw数据发给各中间件处理

3 中间件准备写入网卡的数据 不存在加解密
