### ISSUE TITLE
长时间大流量下载会崩溃

### ISSUE THREAD

**Issue by patrickwangqy** [Srar/node-tap#55]
虽然不知道什么原因，我下载一个25G大小的文件，速度大概10MB/s，但是下载几分钟程序就自己退出了。有什么办法找到原因？

**Comment by Srar** [comment]
内部实现tcp seq自增后 因为是弱类型语言不会溢出 强类型语言会溢出处理 所以seq对不上就蹦掉了 这个当初开发时候只考虑UDP转发为主 TCP转发为辅. 这个问题会稍后尝试修复.

**Comment by patrickwangqy** [comment]
好的，请问现在有什么临时的解决方式嘛-_-

**Comment by Srar** [comment]
用闭源的sstap

**Comment by patrickwangqy** [comment]
好吧，我还是期待你早些解决吧-_-

**Comment by patrickwangqy** [comment]
请问大佬大概什么时候能开始修复这个bug呢？

**Comment by Srar** [comment]
目前工作比较忙 需要鸽一段时间

Patrick Wang <notifications@github.com>于2018年9月17日 周一16:51写道：

**Comment by Srar** [comment]
已经修复下载时单个TCP链接超过4G流量时候崩溃的问题. 上传还有同样的问题暂时懒得修.

https://github.com/Srar/node-tap/releases/tag/1.33

可以尝试下还会不会崩溃.
