### ISSUE TITLE
请问这个和我谷歌到的sstap有什么区别？

### ISSUE THREAD

**Issue by coldeve** [Srar/node-tap#56]

**Comment by Srar** [comment]
开源 闭源区别 同时sstap更加稳定

coldeve <notifications@github.com>于2018年9月12日 周三14:02写道：

**Comment by coldeve** [comment]
那请问这个代码设计上有没有考虑在mac上运行？

**Comment by Srar** [comment]
大部分是通用的 tap虚拟网卡部分需要修改

coldeve <notifications@github.com>于2018年9月12日 周三14:10写道：

**Comment by coldeve** [comment]
请问支持自定义规则吗？比如自定义域名/ip/端口/泛域名？

**Comment by Srar** [comment]
不支持

**Comment by NormanBB** [comment]
@Srar 那么目前版本支持使用SStap的rules来修改Windows路由表吗？

**Comment by Srar** [comment]
@NormanBB 支持的, 同时也能用cmd直接操作路由表
