### ISSUE TITLE
如何使用

### ISSUE THREAD

**Issue by a15945675321** [Srar/node-tap#59]
請問怎麼使用？
已經下載已經打包完的版本。

已經安裝安裝Npcap（Windows10），並勾上Install Npcap in WinPcap API-compatible Mode。

但是使用管理員權限CMD命令運行節點sstap。

我卡在命令說
沒有.\sstap.exe
這種文件

請問我該怎麼解決

**Comment by a15945675321** [comment]
Releases中下载已经打包完的版本
要跟sstap.exe放一起嗎？

**Comment by a15945675321** [comment]
我在sstap.exe
目錄 輸入命令
他是執行sstap.exe(打開程序)

**Comment by Srar** [comment]
Releases中的压缩包已经包含了sstap.exe

**Comment by a15945675321** [comment]
疑...我怎麼沒有
難道我下載錯？1.33

**Comment by Srar** [comment]
* node-sstap.rar <- 下载这个
* Source code(zip) 源码
* Source code(tar.gz) 源码

**Comment by a15945675321** [comment]
我在試試~謝謝你
我看來是下載錯了

**Comment by a15945675321** [comment]
想再問
如何恢復？
重新快開機嗎？

**Comment by Srar** [comment]
没懂啥意思

**Comment by a15945675321** [comment]
沒事
這個是要搭配
Shadowsocks
使用的吧？

**Comment by Srar** [comment]
是的

**Comment by a15945675321** [comment]
已經可以使用~謝謝
請問 支持 自定義路由表规则 嗎?
怎麼使用~?

**Comment by Srar** [comment]
Readme中有写哪个参数可以指定路由表

a15945675321 <notifications@github.com>于2018年12月21日 周五03:34写道：

**Comment by a15945675321** [comment]
還是不懂怎用~
不過我用了gui

**Comment by a15945675321** [comment]
routes
這個參數嗎？
也能指定文件名

**Comment by Srar** [comment]
是的
