### ISSUE TITLE
怎么搭配“无界”翻墙软件使用？

### ISSUE THREAD

**Issue by anlexN** [Srar/node-tap#60]
一直都是配置不成功
```javascript
.\sstap.exe --host 192.168.199.170 --port 9667
Usage: D:\tool\GWF\node-sstap\node-sstap\sstap.exe C:\snapshot\node-tap\output\test.js --host [shadowsocks host] --port [shadowsocks port] --passwd
[shadowsocks password] --xtudp [x times udp packets]

Options:
  --xtudp      [default: 1]
  --host
  --port
  --passwd
  --method
  --tcphost
  --tcpport
  --tcppasswd
  --tcpmethod
  --udphost
  --udpport
  --udppasswd
  --udpmethod
  --dns        [default: "8.8.8.8"]
  --v6dns      [default: "2001:4860:4860::8888"]
  --skipdns    [default: "false"]
  --disablev6  [default: "true"]
  --routes     [default: "0.0.0.0/0"]
```

![image](https://user-images.githubusercontent.com/8686739/51591592-6a0e8480-1f28-11e9-9931-8d92ccc55c51.png)

**Comment by Srar** [comment]
目前只支持ss协议 不支持http https代理

**Comment by anlexN** [comment]
什么时候支持http https代理？

**Comment by Srar** [comment]
永远不会支持

anlex N <notifications@github.com>于2019年1月23日 周三16:22写道：

**Comment by anlexN** [comment]
可以告诉我为什么吗？

**Comment by Srar** [comment]
http代理限制不适用于tcp udp转发

**Comment by huangdog** [comment]
可以用glider来将其转成ss协议
上config：

==========分割线====================
verbose=True

listen=ss://AES-256-CFB:1234@:8449
listen=uottun
listen=udptun
#ss://加密方式：密码@端口

forward=socks5://localhost:9666

==========分割线====================
glider:https://github.com/nadoo/glider

希望大家多多支持这个项目啊（这个项目不是我的）
