### ISSUE TITLE
想弄懂你的代码

### ISSUE THREAD

**Issue by icebear1992** [Srar/node-tap#62]
本人平时只用java，python，js，请问只学TypeScript能弄懂这些代码吗，有点摸不着头脑，我看有很多cpp文件啊，那个要管吗

**Comment by icebear1992** [comment]
对了，我想重新编译在32位的windows操作系统上用，请给我个大概指路方向。。是用VS打开然后32位平台编译吗

**Comment by Srar** [comment]
C++是nodejs的native模块 负责暴露winapi给nodejs调用 

编译教程见:

https://github.com/Srar/node-tap/wiki/%E5%A6%82%E4%BD%95%E6%89%93%E5%8C%85%E6%88%90%E5%8F%AF%E6%89%A7%E8%A1%8C%E6%96%87%E4%BB%B6
