### ISSUE TITLE
win10中可供替代npcap的选择：win10pcap

### ISSUE THREAD

**Issue by SmRiley** [Srar/node-tap#66]
Win10Pcap是由日本筑波大学计算机科学博士生Daiyuu Nobori编写的个人项目 。Win10Pcap的很多部分都来自 WinPcap。

Win10Pcap具有以下功能：

Win10Pcap在x86和x64上与Windows 10一起稳定运行。
Win10Pcap在NDIS 6.x驱动程序模型中实现。
（最初的WinPcap是在NDIS 5.x驱动程序模型中实现的。）
Win10Pcap还可以在x86和x64上与Windows 8.1,8,7，Server 2016，Server 2012 R2，Server 2012和Server 2008 R2一起使用。
Win10Pcap是GPLv2许可下的 开源软件。
Win10Pcap支持 捕获IEEE802.1Q VLAN标记。
Win10Pcap修复了原始WinPcap上的NIC枚举错误。
WinPcap只能枚举启动时存在的NIC。无法枚举在引导时间之后添加的任何NIC。
Win10Pcap可以正确枚举所有现有NIC，包括在引导时间之后添加的NIC。
Win10Pcap支持最多10,000个八位字节的巨型帧。
Win10Pcap与原始WinPcap DLL具有二进制兼容性。
内核模式Win10Pcap设备驱动程序已于2015年6月8日获得Microsoft的“Windows 10 Compatible”徽标

测试中配合node-tap并无任何问题(这是当然)，且安装更为简洁快速.

官网：http://www.win10pcap.org

**Comment by SmRiley** [comment]
此项仅为建议，如无问题我一段时间后会关闭此lssues（您也可以直接关闭）

**Comment by Srar** [comment]
感谢建议 我稍作测试在readme中注明

**Comment by Srar** [comment]
关于win10pcap建议已经写在readme中了 谢谢
