### ISSUE TITLE
默认dns打开谷歌,steam社区等网页会出现证书错误的现象

### ISSUE THREAD

**Issue by SmRiley** [Srar/node-tap#70]
![360截图183408099413699](https://user-images.githubusercontent.com/45205313/62595145-bdb64d80-b90f-11e9-85f9-d25135f1bad6.png)
难道是线路问题?另外skipdns是使用电脑自身dns的意思么?对游戏加速来说是指定dns还是不指定比较好一点呢?

**Comment by Srar** [comment]
访问别的SSL服务没问题的话那么就是线路问题.

SkipDNS是使用电脑本身DNS, 是否加上这个参数还是主要看游戏. 个人建议是大多数场景不要加这个参数.

SmRiley <notifications@github.com>于2019年8月7日 周三12:36写道：

**Comment by SmRiley** [comment]
原因找到了,是服务器没有开启udp导致的.谢谢
