### ISSUE TITLE
求提供none加密

### ISSUE THREAD

**Issue by huangdog** [Srar/node-tap#71]
本人使用node-tap 是配合  glider  把ssr/无界  转成ss来使用的，在局域网内，在同一台机器上，不需要加密，希望作者为node-tap提供一个none加密，谢谢

glider支持none加密的ss协议的
ss://DUMMY@:8443
连接glider分出的ss时，使用客户端例如ssr，协议origin和混淆plain ，加密选择none，密码随便填。

**Comment by Srar** [comment]
抱歉 这个加密暂时目前不打算支持
